title: Jamstatic
description: L'actualité autour des générateurs de site statique et de la JAMStack
url: https://jamstatic.fr

permalink: "/:year/:month/:day/:title/"
lang: fr
timezone: Europe/Paris

repository: jamstatic/jamstatic-fr

github:
  username: jamstatic
  source:
    branch: master

email: contact@jamstatic.fr

twitter:
  username: jamstatic_fr

social:
  type: organization
  links:
  - https://twitter.com/jamstatic_fr
  - https://github.com/jamstatic

google_site_verification: lrEoUhopZf6zuDH_kdABgRxWc0uAVSlXBftczsGVL10

analytics:
  google:
    tracking_id: UA-75833986-1

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: compressed

# Liquid
strict_front_matter: true
liquid:
  error_mode: strict

livereload: true

collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    author: Frank Taillandier

include:
  - _headers

exclude:
- ".editorconfig"
- ".forestryio"
- ".gitignore"
- ".rubocop.yml"
- ".travis.yml"
- Gemfile
- Gemfile.lock
- LICENSE
- node_modules
- Rakefile
- README.md
- script

plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-gist
- jekyll-github-metadata
- jekyll-include-cache
- jekyll-mentions
- jekyll-octicons
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-typogrify
- jemoji
